M48
; DRILL file {KiCad (6.0.10)} date Sun Jan 22 23:50:18 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-22T23:50:18+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X3.1662Y-4.8076
X3.3938Y-4.8076
X3.6062Y-4.8076
X3.8338Y-4.8076
T0
M30
